//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiTenantApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiTenantApi.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToRAFgm0+cdkzLSE5spRV4NGb6zhJMhAC5wC7T1mCQKh0Zy4OjbEItW+6MudqRg6mbhP7dQ9UJc2NzL2rTMk8hCxCLONh/RZpOAI/lgAIAk=.
        /// </summary>
        internal static string localhost {
            get {
                return ResourceManager.GetString("localhost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LQM3K5jIIaUFGz6t0SFC1+jqTWKUsxGEoYBe7vvOuhW4USUP/c1unmhratSXFMge.
        /// </summary>
        internal static string localhost_TokenKey {
            get {
                return ResourceManager.GetString("localhost.TokenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToRAFgm0+cdkzLSE5spRV4NGb6zhJMhAC5wC7T1mCQItPRb8oPAE6G5Iylm7rjioQk0vg1CuYjlvdDg7NhA6hQ/lYWPPkM9B2BmvUjzS0A4=.
        /// </summary>
        internal static string tenant1 {
            get {
                return ResourceManager.GetString("tenant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BNTw/49ciYikiCjKdBEAkYTDXCeioU0JmOXzaK3hEZ/GmK9FwPaXoPoBNZR5zKFc.
        /// </summary>
        internal static string tenant1_TokenKey {
            get {
                return ResourceManager.GetString("tenant1.TokenKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToRAFgm0+cdkzLSE5spRV4NGb6zhJMhAC5wC7T1mCQL/70LL6oIl4HkU685yPGXBmo4T2uX8UtZJeSqHxk6DSBz12u8EXoDIn9kIbyQ9oMY=.
        /// </summary>
        internal static string tenant2 {
            get {
                return ResourceManager.GetString("tenant2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gfiMUQJpckIvwtKH/fp2wPsEjAyx+qUiPEBX6TGNfiNnojbdPxE7H4gdKErOAA7c.
        /// </summary>
        internal static string tenant2_TokenKey {
            get {
                return ResourceManager.GetString("tenant2.TokenKey", resourceCulture);
            }
        }
    }
}
